using System.Linq.Expressions;

namespace ElBruno.AotMapper.EntityFramework;

/// <summary>
/// Extension methods for EF Core IQueryable projection using AotMapper.
/// NOTE: Actual ProjectTo methods are generated by the source generator for each mapping.
/// This class provides base infrastructure and helper methods.
/// </summary>
public static class AotMapperQueryableExtensions
{
    /// <summary>
    /// Helper to apply a projection expression to a queryable.
    /// Used by generated ProjectTo methods.
    /// </summary>
    public static IQueryable<TDestination> ApplyProjection<TSource, TDestination>(
        this IQueryable<TSource> source,
        Expression<Func<TSource, TDestination>> projection)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(projection);
        return source.Select(projection);
    }
}
