using System.Linq;
using System.Text;
using ElBruno.AotMapper.Generator.Models;

namespace ElBruno.AotMapper.Generator;

internal static class MappingEmitter
{
    public static string EmitMappingClass(MappingModel model)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        
        if (!string.IsNullOrEmpty(model.DestinationTypeNamespace))
        {
            sb.AppendLine($"namespace {model.DestinationTypeNamespace}");
            sb.AppendLine("{");
        }

        var extensionClassName = $"{model.DestinationTypeName}MappingExtensions";
        sb.AppendLine($"    public static partial class {extensionClassName}");
        sb.AppendLine("    {");

        // Generate single object mapping method
        EmitSingleMappingMethod(sb, model);
        
        sb.AppendLine();
        
        // Generate collection mapping method
        EmitCollectionMappingMethod(sb, model);

        // Generate EF Core projection method if compatible
        var (projectionCode, incompatibilityReason) = EfProjectionEmitter.TryEmitProjectionMethod(model);
        if (projectionCode != null)
        {
            sb.AppendLine();
            sb.Append(projectionCode);
        }
        else if (incompatibilityReason != null)
        {
            sb.AppendLine();
            sb.AppendLine($"        // ProjectTo{model.DestinationTypeName}() not generated: {incompatibilityReason}");
        }

        sb.AppendLine("    }");
        
        if (!string.IsNullOrEmpty(model.DestinationTypeNamespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitSingleMappingMethod(StringBuilder sb, MappingModel model)
    {
        var methodName = $"To{model.DestinationTypeName}";
        
        sb.AppendLine($"        public static {model.DestinationTypeFullName} {methodName}(this {model.SourceTypeFullName} source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null)");
        sb.AppendLine("                throw new System.ArgumentNullException(nameof(source));");
        sb.AppendLine();

        if (model.UseConstructorMapping)
        {
            EmitConstructorMapping(sb, model);
        }
        else
        {
            EmitObjectInitializerMapping(sb, model);
        }

        sb.AppendLine("        }");
    }

    private static void EmitConstructorMapping(StringBuilder sb, MappingModel model)
    {
        sb.Append($"            return new {model.DestinationTypeFullName}(");
        
        var parameters = model.PropertyMappings
            .Where(m => !m.IsIgnored && model.ConstructorParameterNames.Contains(m.DestinationPropertyName))
            .OrderBy(m => model.ConstructorParameterNames.IndexOf(m.DestinationPropertyName))
            .ToList();

        for (int i = 0; i < parameters.Count; i++)
        {
            if (i > 0)
                sb.Append(",");
            
            sb.AppendLine();
            sb.Append("                ");
            sb.Append(EmitPropertyMapping(parameters[i]));
        }

        sb.AppendLine();
        sb.AppendLine("            );");
    }

    private static void EmitObjectInitializerMapping(StringBuilder sb, MappingModel model)
    {
        sb.AppendLine($"            return new {model.DestinationTypeFullName}");
        sb.AppendLine("            {");

        var properties = model.PropertyMappings.Where(m => !m.IsIgnored).ToList();
        
        for (int i = 0; i < properties.Count; i++)
        {
            var mapping = properties[i];
            sb.Append($"                {mapping.DestinationPropertyName} = ");
            sb.Append(EmitPropertyMapping(mapping));
            
            if (i < properties.Count - 1)
                sb.Append(",");
            
            sb.AppendLine();
        }

        sb.AppendLine("            };");
    }

    private static string EmitPropertyMapping(PropertyMapping mapping)
    {
        var sourceAccess = $"source.{mapping.SourcePropertyName}";

        switch (mapping.Strategy)
        {
            case MappingStrategy.Direct:
                return sourceAccess;

            case MappingStrategy.NestedMapping:
                if (mapping.IsNullable)
                {
                    var destTypeName = ExtractSimpleTypeName(mapping.DestinationPropertyType);
                    return $"{sourceAccess}?.To{destTypeName}()";
                }
                else
                {
                    var destTypeName = ExtractSimpleTypeName(mapping.DestinationPropertyType);
                    return $"{sourceAccess}.To{destTypeName}()";
                }

            case MappingStrategy.CollectionMapping:
                return EmitCollectionMapping(mapping, sourceAccess);

            case MappingStrategy.DictionaryMapping:
                return EmitDictionaryMapping(mapping, sourceAccess);

            case MappingStrategy.EnumToEnum:
                return $"({mapping.DestinationPropertyType}){sourceAccess}";

            case MappingStrategy.EnumToString:
                if (mapping.IsNullable)
                    return $"{sourceAccess}?.ToString()";
                return $"{sourceAccess}.ToString()";

            case MappingStrategy.StringToEnum:
                var enumType = mapping.DestinationPropertyType.TrimEnd('?');
                if (mapping.IsNullable)
                    return $"string.IsNullOrEmpty({sourceAccess}) ? null : System.Enum.Parse<{enumType}>({sourceAccess})";
                return $"System.Enum.Parse<{enumType}>({sourceAccess})";

            case MappingStrategy.EnumToInt:
                return $"({mapping.DestinationPropertyType}){sourceAccess}";

            case MappingStrategy.IntToEnum:
                return $"({mapping.DestinationPropertyType}){sourceAccess}";

            case MappingStrategy.CustomConverter:
                return $"new {mapping.ConverterType}().Convert({sourceAccess})";

            default:
                return sourceAccess;
        }
    }

    private static string EmitCollectionMapping(PropertyMapping mapping, string sourceAccess)
    {
        // Extract element types
        var sourceElementType = ExtractCollectionElementType(mapping.SourcePropertyType);
        var destElementType = ExtractCollectionElementType(mapping.DestinationPropertyType);

        if (string.IsNullOrEmpty(sourceElementType) || string.IsNullOrEmpty(destElementType))
        {
            return sourceAccess;
        }

        var destTypeName = ExtractSimpleTypeName(destElementType);
        var conversionExpr = $"x => x.To{destTypeName}()";

        if (mapping.IsNullable)
        {
            return $"{sourceAccess}?.Select({conversionExpr}).ToList()";
        }
        else
        {
            return $"{sourceAccess}.Select({conversionExpr}).ToList()";
        }
    }

    private static string EmitDictionaryMapping(PropertyMapping mapping, string sourceAccess)
    {
        // For dictionaries, we just copy the dictionary as-is (shallow copy)
        // This handles Dictionary<K,V> and IReadOnlyDictionary<K,V>
        var destType = mapping.DestinationPropertyType;
        
        if (mapping.IsNullable)
        {
            // For nullable dictionaries, check for null and create new dictionary
            if (destType.Contains("IReadOnlyDictionary"))
            {
                return $"{sourceAccess} != null ? new System.Collections.Generic.Dictionary<{ExtractDictionaryTypeArgs(destType)}>({sourceAccess}) : null";
            }
            else
            {
                return $"{sourceAccess} != null ? new System.Collections.Generic.Dictionary<{ExtractDictionaryTypeArgs(destType)}>({sourceAccess}) : null";
            }
        }
        else
        {
            // Non-nullable dictionary
            if (destType.Contains("IReadOnlyDictionary"))
            {
                return $"new System.Collections.Generic.Dictionary<{ExtractDictionaryTypeArgs(destType)}>({sourceAccess})";
            }
            else
            {
                return $"new System.Collections.Generic.Dictionary<{ExtractDictionaryTypeArgs(destType)}>({sourceAccess})";
            }
        }
    }

    private static void EmitCollectionMappingMethod(StringBuilder sb, MappingModel model)
    {
        var methodName = $"To{model.DestinationTypeName}List";
        
        sb.AppendLine($"        public static System.Collections.Generic.List<{model.DestinationTypeFullName}> {methodName}(this System.Collections.Generic.IEnumerable<{model.SourceTypeFullName}> source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null)");
        sb.AppendLine("                throw new System.ArgumentNullException(nameof(source));");
        sb.AppendLine();
        sb.AppendLine($"            return source.Select(x => x.To{model.DestinationTypeName}()).ToList();");
        sb.AppendLine("        }");
    }

    private static string ExtractSimpleTypeName(string fullTypeName)
    {
        // Remove "global::" prefix
        var name = fullTypeName.Replace("global::", "");
        
        // Remove namespace and get just the type name
        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
        {
            name = name.Substring(lastDot + 1);
        }

        // Remove nullable marker
        name = name.TrimEnd('?');

        // Remove generic parameters for simple name
        var genericStart = name.IndexOf('<');
        if (genericStart >= 0)
        {
            name = name.Substring(0, genericStart);
        }

        return name;
    }

    private static string ExtractCollectionElementType(string collectionType)
    {
        // Handle array types
        if (collectionType.EndsWith("[]"))
        {
            return collectionType.Substring(0, collectionType.Length - 2);
        }

        // Handle generic collections
        var genericStart = collectionType.IndexOf('<');
        var genericEnd = collectionType.LastIndexOf('>');
        
        if (genericStart >= 0 && genericEnd > genericStart)
        {
            return collectionType.Substring(genericStart + 1, genericEnd - genericStart - 1);
        }

        return string.Empty;
    }

    private static string ExtractDictionaryTypeArgs(string dictionaryType)
    {
        // Extract "TKey, TValue" from "Dictionary<TKey, TValue>" or similar
        var genericStart = dictionaryType.IndexOf('<');
        var genericEnd = dictionaryType.LastIndexOf('>');
        
        if (genericStart >= 0 && genericEnd > genericStart)
        {
            return dictionaryType.Substring(genericStart + 1, genericEnd - genericStart - 1);
        }

        return "object, object"; // Fallback
    }
}
